<?php
/**
 * Ash Core Extension
 *
 * Maintains common settings and configuration for AAI-built Magento websites.
 *
 * @category    Ash
 * @package     Ash_Core
 * @copyright   Copyright (c) 2012 August Ash, Inc. (http://www.augustash.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<style type="text/css">
    #ash-maintenance-reminder {
        position: relative; width: 100%; padding: .5em; text-align: center; z-index: 1000; border:1px solid #f16048 !important; background:#faebe7; color:#df280a !important;
    }
    #ash-maintenance-reminder h1 {margin:0; padding:0; display:inline; color:#df280a; font-size:1.2em;
    }
</style>
<div id="ash-maintenance-reminder">
    <h1>Maintenance Mode Active</h1>
</div>
